# Render Deployment Configuration
# This file helps configure the deployment on Render

# Build Command (for Python applications)
# pip install -r requirements.txt

# Start Command
gunicorn app:app --bind 0.0.0.0:$PORT

# Python Version
python-3.13

# Environment Variables (add these in Render dashboard)
# FLASK_ENV=production
# SECRET_KEY=your-secret-key-here

# Database Configuration
# The app uses SQLite by default, but for production you might want PostgreSQL
# DATABASE_URL=postgresql://user:password@host:port/database

# Static Files Configuration
# The app serves static files from the 'static' directory automatically
